version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: passbook_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: quan_ly_so_tiet_kiem
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: